"use client";

import { useEffect, useState } from "react";

type Review={id:string;user_id:string;email:string;reason:string;created_at:string};
type Envelope<T>={data?:T;error?:{message:string}};

export default function CampusReviewsPage(){
  const [csrf,setCSRF]=useState("");const [items,setItems]=useState<Review[]>([]);const [reason,setReason]=useState("");const [problem,setProblem]=useState("");const [message,setMessage]=useState("");
  async function load(){try{const session=await fetch("/api/v1/session",{cache:"no-store"}).then(r=>r.json() as Promise<Envelope<{authenticated:boolean;user?:{campus_admin:boolean;mfa_verified:boolean};csrf_token?:string}>>);if(!session.data?.authenticated){location.assign("/login");return}setCSRF(session.data.csrf_token??"");if(!session.data.user?.campus_admin||!session.data.user.mfa_verified){setProblem("A campus administrator session with fresh MFA is required.");return}const result=await fetch("/api/v1/admin/campus-review-requests",{cache:"no-store"}).then(r=>r.json() as Promise<Envelope<{items:Review[]}>>);if(result.error)throw new Error(result.error.message);setItems(result.data?.items??[])}catch(e){setProblem(e instanceof Error?e.message:"Campus review queue could not load.")}}
  useEffect(()=>{void load()},[]);
  async function decide(id:string,decision:"approved"|"rejected"){setProblem("");setMessage("");try{const response=await fetch(`/api/v1/admin/campus-review-requests/${id}/decision`,{method:"POST",headers:{"Content-Type":"application/json","X-CSRF-Token":csrf},body:JSON.stringify({decision,reason})});const result=await response.json() as Envelope<{state:string}>;if(!response.ok||result.error)throw new Error(result.error?.message??"Review decision failed.");setItems(value=>value.filter(item=>item.id!==id));setReason("");setMessage(`Request ${decision}. Administrative approval does not verify mailbox ownership.`)}catch(e){setProblem(e instanceof Error?e.message:"Review decision failed.")}}
  return <main className="account-shell"><a className="skip-link" href="#reviews">Skip to review queue</a><header className="topbar"><a className="brand" href="/">PeerGit</a><nav aria-label="Account"><a href="/onboarding">Onboarding</a></nav></header><section id="reviews" className="content" aria-labelledby="review-title"><p className="eyebrow">Campus administration</p><h1 id="review-title">Campus verification reviews</h1><p>Review campus affiliation requests for your campus. Your decision needs fresh MFA and a reason. Approval grants student access but does not verify a mailbox.</p><label htmlFor="review-reason">Decision reason</label><textarea id="review-reason" value={reason} onChange={e=>setReason(e.target.value)} minLength={8} maxLength={2000} rows={3}/>{problem&&<p className="form-error" role="alert">{problem}</p>}{message&&<p className="form-success" role="status">{message}</p>}<ul className="campus-users">{items.map(item=><li key={item.id}><div><strong>{item.email}</strong><p>{item.reason}</p><small>{new Date(item.created_at).toLocaleString()}</small></div><span className="member-actions"><button className="primary-button" disabled={reason.trim().length<8} onClick={()=>void decide(item.id,"approved")}>Approve student access</button><button className="secondary-button" disabled={reason.trim().length<8} onClick={()=>void decide(item.id,"rejected")}>Reject</button></span></li>)}</ul>{items.length===0&&!problem&&<p role="status">No pending requests.</p>}</section></main>;
}
