"use client";

import { FormEvent, useEffect, useState } from "react";
import { AccountPanel } from "@/components/account/account-panel";

type Envelope<T> = { data?: T; error?: { message: string } };
type Status = { campus_verified: boolean; campus_id: string; account_type: string; pending_challenge?: { challenge_id: string; email: string; expires_at: string } };

export default function OnboardingPage() {
  const [csrf,setCSRF]=useState(""); const [email,setEmail]=useState(""); const [campus,setCampus]=useState("");const [reviewReason,setReviewReason]=useState("");const [status,setStatus]=useState<Status|null>(null); const [problem,setProblem]=useState(""); const [message,setMessage]=useState("");
  async function load(){try{const session=await fetch("/api/v1/session",{cache:"no-store"}).then(r=>r.json() as Promise<Envelope<{authenticated:boolean;csrf_token?:string}>>);if(!session.data?.authenticated){location.assign("/login");return}setCSRF(session.data.csrf_token??"");const result=await fetch("/api/v1/me/onboarding",{cache:"no-store"}).then(r=>r.json() as Promise<Envelope<Status>>);if(result.error)throw new Error(result.error.message);setStatus(result.data??null)}catch(e){setProblem(e instanceof Error?e.message:"Onboarding could not load.")}}
  useEffect(()=>{void load()},[]);
  async function requestCode(event:FormEvent){event.preventDefault();setProblem("");setMessage("");try{const response=await fetch("/api/v1/me/campus-verification/challenges",{method:"POST",headers:{"Content-Type":"application/json","X-CSRF-Token":csrf},body:JSON.stringify({campus_email:email})});const result=await response.json() as Envelope<{challenge_id:string}>;if(!response.ok||result.error)throw new Error(result.error?.message??"Could not send the verification email.");setMessage("A verification link and six-digit code were sent. Check your campus inbox.");await load()}catch(e){setProblem(e instanceof Error?e.message:"Could not send the verification email.")}}
  async function requestReview(event:FormEvent){event.preventDefault();setProblem("");setMessage("");try{const response=await fetch("/api/v1/me/campus-review-requests",{method:"POST",headers:{"Content-Type":"application/json","X-CSRF-Token":csrf},body:JSON.stringify({campus_id:campus,campus_email:email,reason:reviewReason})});const result=await response.json() as Envelope<{state:string}>;if(!response.ok||result.error)throw new Error(result.error?.message??"Campus review request could not be submitted.");setMessage("Your request is in the campus review queue.")}catch(e){setProblem(e instanceof Error?e.message:"Campus review request could not be submitted.")}}
  return <main>
    <a className="skip-link" href="#onboarding-content">Skip to content</a>
    <header className="topbar"><a className="brand" href="/">PeerGit</a><nav aria-label="Account"><a href="/">Explore public projects</a></nav></header>
    <section id="onboarding-content" className="hero" aria-labelledby="onboarding-title">
      <p className="eyebrow">One more step</p><h1 id="onboarding-title">Set up your PeerGit account</h1>
      <p className="intro">Your GitHub sign-in does not verify campus membership. Campus access starts after you confirm your campus email.</p>
    </section>
      <AccountPanel />
    <section className="account-panel" aria-labelledby="campus-verify-title"><p className="eyebrow">Your account</p><h2 id="campus-verify-title">{status?.campus_verified?"Campus verified":status?.campus_id?"Campus access inactive":"Verify your campus email"}</h2>{status?.campus_verified?<p>Your campus access is active. <a href="/">Continue to PeerGit</a>.</p>:status?.campus_id?<p>Your campus access is inactive. Your account and personal profile remain available; contact a campus administrator about restoring access.</p>:<><p>Use an approved campus email. We will send a ten-minute link and a six-digit fallback code.</p><form className="account-form" onSubmit={requestCode}><label htmlFor="campus-email">Campus email</label><input id="campus-email" type="email" autoComplete="email" value={email} onChange={e=>setEmail(e.target.value)} /><button className="primary-button" type="submit" disabled={!csrf||!email}>Send verification email</button></form>{status?.pending_challenge&&<p role="status">A message was sent to {status.pending_challenge.email}. <a href={`/onboarding/verify?challenge_id=${encodeURIComponent(status.pending_challenge.challenge_id)}`}>Enter its code</a>.</p>}<details><summary>My campus email is not supported</summary><form className="account-form" onSubmit={requestReview}><label htmlFor="campus-id">Campus ID or slug</label><input id="campus-id" required value={campus} onChange={e=>setCampus(e.target.value)} /><label htmlFor="review-reason">Why should the campus review this request?</label><textarea id="review-reason" required minLength={8} maxLength={2000} rows={4} value={reviewReason} onChange={e=>setReviewReason(e.target.value)} /><button className="secondary-button" type="submit" disabled={!csrf}>Request campus review</button></form></details></>}{problem&&<p className="form-error" role="alert">{problem}</p>}{message&&<p className="form-success" role="status">{message}</p>}</section>
  </main>;
}
