"use client";

import { FormEvent, useCallback, useEffect, useState } from "react";

type Envelope<T>={data?:T;error?:{message?:string}};
type Binding={id:string;full_name:string;html_url:string;description:string;default_branch:string;topics:string[];languages:Record<string,number>;readme_markdown:string;access_state:string;sync_health:string;last_synced_at?:string|null;limitations:string};
type Contribution={id:string;kind:string;canonical_id:string;title:string;summary:string;author_name:string;author_login:string;occurred_at?:string|null};
type Snapshot={id:string;ref:string;commit_sha:string;state:string;receipt_at:string;failure_code?:string|null;retry_available?:boolean};
type Data={repository:Binding|null;contributions:Contribution[];snapshots:Snapshot[]};

export function RepositoryOverview({projectID,csrf}:{projectID:string;csrf:string}){
 const [data,setData]=useState<Data>({repository:null,contributions:[],snapshots:[]});const [ref,setRef]=useState("main");const [loading,setLoading]=useState(true);const [busy,setBusy]=useState(false);const [problem,setProblem]=useState("");const [message,setMessage]=useState("");
 const api=useCallback(async<T,>(path:string,init?:RequestInit):Promise<T>=>{const headers=new Headers(init?.headers);if(init?.body)headers.set("Content-Type","application/json");if(init?.method&&init.method!=="GET")headers.set("X-CSRF-Token",csrf);const r=await fetch(path,{...init,headers,cache:"no-store",credentials:"same-origin"});const v=r.status===204?{data:undefined}:await r.json() as Envelope<T>;if(!r.ok)throw new Error(v.error?.message??"Repository request failed.");return v.data as T},[csrf]);
 const refresh=useCallback(async()=>{setLoading(true);try{setData(await api<Data>(`/api/v1/projects/${projectID}/repository`));setProblem("")}catch(e){setProblem(e instanceof Error?e.message:"Repository evidence could not be loaded.")}finally{setLoading(false)}},[api,projectID]);
 useEffect(()=>{void refresh()},[refresh]);
 async function capture(e:FormEvent){e.preventDefault();if(!data.repository)return;setBusy(true);setProblem("");try{await api(`/api/v1/projects/${projectID}/repository/snapshots`,{method:"POST",headers:{"Idempotency-Key":crypto.randomUUID()},body:JSON.stringify({binding_id:data.repository.id,ref})});setMessage("Exact commit receipt recorded; archive capture is running.");await refresh()}catch(x){setProblem(x instanceof Error?x.message:"Snapshot request failed.")}finally{setBusy(false)}}
 async function retry(id:string){setBusy(true);try{await api(`/api/v1/projects/${projectID}/repository/snapshots/${id}/retry`,{method:"POST",body:"{}"});setMessage("Snapshot retry queued for the same commit.");await refresh()}catch(e){setProblem(e instanceof Error?e.message:"Retry failed.")}finally{setBusy(false)}}
 return <section className="repository-panel" aria-labelledby="repository-overview-title"><div className="repository-heading"><div><p className="eyebrow">GitHub project</p><h2 id="repository-overview-title">Repository overview</h2></div><button className="secondary-button" type="button" disabled={loading||busy} onClick={()=>void refresh()}>Refresh</button></div>
 {problem&&<p className="form-error" role="alert">{problem}</p>}{message&&<p className="form-success" role="status">{message}</p>}{loading?<p role="status">Loading repository…</p>:!data.repository?<div className="repository-empty"><p>This older project has no connected repository yet.</p><a className="primary-link" href="/account/github">Connect GitHub and import a repository</a></div>:<>
 <h3><a href={data.repository.html_url} target="_blank" rel="noreferrer">{data.repository.full_name} ↗</a></h3><p>{data.repository.description||"No repository description."}</p><p>{data.repository.access_state.replaceAll("_"," ")} · sync {data.repository.sync_health.replaceAll("_"," ")}{data.repository.last_synced_at?` · ${new Date(data.repository.last_synced_at).toLocaleString()}`:""}</p><p>Default branch: {data.repository.default_branch||"not set"}</p>
 {data.repository.topics.length>0&&<ul className="skill-list">{data.repository.topics.map(t=><li key={t}>{t}</li>)}</ul>}
 {Object.keys(data.repository.languages).length>0&&<p>Languages: {Object.keys(data.repository.languages).join(", ")}</p>}
 <p className="repository-limits">{data.repository.limitations} Files and source browsing stay on GitHub.</p>
 {data.repository.readme_markdown&&<section className="account-form"><h3>README</h3><pre className="readme-text">{data.repository.readme_markdown}</pre></section>}
 <h3>Recent commits, pull requests, and issues</h3>{data.contributions.length?<ul className="repository-activity">{data.contributions.map(c=><li key={c.id}><div><strong>{c.title||c.canonical_id}</strong><p>{c.kind.replaceAll("_"," ")} · {c.author_name||c.author_login||"Unlinked GitHub account"}</p>{c.summary&&<p>{c.summary}</p>}</div><time>{c.occurred_at?new Date(c.occurred_at).toLocaleString():"Date unavailable"}</time></li>)}</ul>:<p>Repository evidence has not synced yet.</p>}
 <form className="repository-capture" onSubmit={capture}><label htmlFor="snapshot-ref">Record an immutable snapshot of a branch, tag, or commit</label><div><input id="snapshot-ref" value={ref} onChange={e=>setRef(e.target.value)} maxLength={255} required/><button className="primary-button" disabled={busy||data.repository.access_state!=="active"}>Capture</button></div></form>
 <h3>Immutable snapshots</h3>{data.snapshots.length?<ul className="repository-snapshots">{data.snapshots.map(s=><li key={s.id}><div><strong>{s.state.replaceAll("_"," ")}</strong><p>{s.ref} → <code>{s.commit_sha.slice(0,12)}</code> · {new Date(s.receipt_at).toLocaleString()}{s.failure_code?` · ${s.failure_code}`:""}</p></div><div className="snapshot-actions">{s.state==="verified"&&<a className="secondary-button" href={`/api/v1/projects/${projectID}/repository/snapshots/${s.id}/download`}>Download</a>}{s.retry_available&&<button className="secondary-button" type="button" onClick={()=>void retry(s.id)} disabled={busy}>Retry same SHA</button>}</div></li>)}</ul>:<p>No snapshots yet.</p>}
 </>}</section>
}
